// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: education.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EducationService_CreateEducation_FullMethodName = "/protos.EducationService/CreateEducation"
	EducationService_UpdateEducation_FullMethodName = "/protos.EducationService/UpdateEducation"
	EducationService_DeleteEducation_FullMethodName = "/protos.EducationService/DeleteEducation"
	EducationService_GetEducation_FullMethodName    = "/protos.EducationService/GetEducation"
	EducationService_GetEducations_FullMethodName   = "/protos.EducationService/GetEducations"
)

// EducationServiceClient is the client API for EducationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EducationServiceClient interface {
	CreateEducation(ctx context.Context, in *CreateEducationRequest, opts ...grpc.CallOption) (*Education, error)
	UpdateEducation(ctx context.Context, in *UpdateEducationRequest, opts ...grpc.CallOption) (*Void, error)
	DeleteEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
	GetEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Education, error)
	GetEducations(ctx context.Context, in *EducationFilter, opts ...grpc.CallOption) (*Educations, error)
}

type educationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEducationServiceClient(cc grpc.ClientConnInterface) EducationServiceClient {
	return &educationServiceClient{cc}
}

func (c *educationServiceClient) CreateEducation(ctx context.Context, in *CreateEducationRequest, opts ...grpc.CallOption) (*Education, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Education)
	err := c.cc.Invoke(ctx, EducationService_CreateEducation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) UpdateEducation(ctx context.Context, in *UpdateEducationRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, EducationService_UpdateEducation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) DeleteEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, EducationService_DeleteEducation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Education, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Education)
	err := c.cc.Invoke(ctx, EducationService_GetEducation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetEducations(ctx context.Context, in *EducationFilter, opts ...grpc.CallOption) (*Educations, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Educations)
	err := c.cc.Invoke(ctx, EducationService_GetEducations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EducationServiceServer is the server API for EducationService service.
// All implementations must embed UnimplementedEducationServiceServer
// for forward compatibility
type EducationServiceServer interface {
	CreateEducation(context.Context, *CreateEducationRequest) (*Education, error)
	UpdateEducation(context.Context, *UpdateEducationRequest) (*Void, error)
	DeleteEducation(context.Context, *ById) (*Void, error)
	GetEducation(context.Context, *ById) (*Education, error)
	GetEducations(context.Context, *EducationFilter) (*Educations, error)
	mustEmbedUnimplementedEducationServiceServer()
}

// UnimplementedEducationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEducationServiceServer struct {
}

func (UnimplementedEducationServiceServer) CreateEducation(context.Context, *CreateEducationRequest) (*Education, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEducation not implemented")
}
func (UnimplementedEducationServiceServer) UpdateEducation(context.Context, *UpdateEducationRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEducation not implemented")
}
func (UnimplementedEducationServiceServer) DeleteEducation(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEducation not implemented")
}
func (UnimplementedEducationServiceServer) GetEducation(context.Context, *ById) (*Education, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEducation not implemented")
}
func (UnimplementedEducationServiceServer) GetEducations(context.Context, *EducationFilter) (*Educations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEducations not implemented")
}
func (UnimplementedEducationServiceServer) mustEmbedUnimplementedEducationServiceServer() {}

// UnsafeEducationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EducationServiceServer will
// result in compilation errors.
type UnsafeEducationServiceServer interface {
	mustEmbedUnimplementedEducationServiceServer()
}

func RegisterEducationServiceServer(s grpc.ServiceRegistrar, srv EducationServiceServer) {
	s.RegisterService(&EducationService_ServiceDesc, srv)
}

func _EducationService_CreateEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEducationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).CreateEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_CreateEducation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).CreateEducation(ctx, req.(*CreateEducationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_UpdateEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEducationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).UpdateEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_UpdateEducation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).UpdateEducation(ctx, req.(*UpdateEducationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_DeleteEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).DeleteEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_DeleteEducation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).DeleteEducation(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetEducation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetEducation(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetEducations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EducationFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetEducations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetEducations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetEducations(ctx, req.(*EducationFilter))
	}
	return interceptor(ctx, in, info, handler)
}

// EducationService_ServiceDesc is the grpc.ServiceDesc for EducationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EducationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.EducationService",
	HandlerType: (*EducationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEducation",
			Handler:    _EducationService_CreateEducation_Handler,
		},
		{
			MethodName: "UpdateEducation",
			Handler:    _EducationService_UpdateEducation_Handler,
		},
		{
			MethodName: "DeleteEducation",
			Handler:    _EducationService_DeleteEducation_Handler,
		},
		{
			MethodName: "GetEducation",
			Handler:    _EducationService_GetEducation_Handler,
		},
		{
			MethodName: "GetEducations",
			Handler:    _EducationService_GetEducations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "education.proto",
}
